### PR TITLE
HW2

### PR DESCRIPTION
**Pull request by Mahsa-kz**
Questions 1 and 2 are uploaded.

### CODE REVIEW

**Comment by fangq** [comment]
hi @Mahsa-kz, the changes in this pull request is empty.

https://github.com/fangq/BIOE5060_Fall_2024/pull/16/files

I am closing this one - please do not create new pull requests. just go back to your patch-2 branch, and continue making changes - make sure you add the missing files and push your changes to your github. It should then show up in #14

**Comment by Mahsa-kz** [comment]
> hi @Mahsa-kz, the changes in this pull request is empty.
> 
> https://github.com/fangq/BIOE5060_Fall_2024/pull/16/files
> 
> I am closing this one - please do not create new pull requests. just go back to your patch-2 branch, and continue making changes - make sure you add the missing files and push your changes to your github. It should then show up in #14

Hi,
I was not able to access patch-2 again, but I had uploaded everything in the main branch. Is that okay?
image

**Comment by Mahsa-kz** [comment]
> > hi @Mahsa-kz, the changes in this pull request is empty.
> > https://github.com/fangq/BIOE5060_Fall_2024/pull/16/files
> > I am closing this one - please do not create new pull requests. just go back to your patch-2 branch, and continue making changes - make sure you add the missing files and push your changes to your github. It should then show up in #14
> 
> Hi, I was not able to access patch-2 again, but I had uploaded everything in the main branch. Is that okay? image

I am sorry to ask, but can you see my uploads in the main branch or I should have requested a pull there?
image

**Comment by fangq** [comment]
what branch are these changes made? you need to create a pull request from that branch against my repository.

because your previous Pull request #14 is from branch `branch-2`, so, alternatively, if you can add your changes to branch-2, then, the #14 will show your changes automatically.

**Comment by fangq** [comment]
additional tutorials on creating PR can be found here

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

https://www.youtube.com/watch?v=nCKdihvneS0&t=108s

https://www.youtube.com/watch?v=jRLGobWwA3Y

**Comment by Mahsa-kz** [comment]
> what branch are these changes made? you need to create a pull request from that branch against my repository.
> 
> because your previous Pull request #14 is from [branch `patch-2`](https://github.com/Mahsa-kz/BIOE5060_Fall_2024/tree/patch-2), so, alternatively, if you can add your changes to branch-2, then, the #14 will show your changes automatically.

These were made to the main branch. I just requested a pull request for it.
Sorry for the inconvenience and thanks for your replies.

**Comment by Mahsa-kz** [comment]
> additional tutorials on creating PR can be found here
> 
> https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
> 
> https://www.youtube.com/watch?v=nCKdihvneS0&t=108s
> 
> https://www.youtube.com/watch?v=jRLGobWwA3Y

Thank you. I will go through them.

**Pull request closed without merging**
