### PR TITLE
IvonneL_HW2_Q1

### PR DESCRIPTION
**Pull request by ivonne0126**
Added screenshot of Linux system with readme file

### CODE REVIEW

**Comment by fangq** [comment]
@ivonne0126, thanks for the submission - would it be possible to take a new screenshot with some programs - such as a file browser or terminal window opened? you can replace the existing screenshot and make a new commit.

**Comment by fangq** [comment]
thank you @ivonne0126. In the assignment instruction:
> 5. Add a README.md file, describing the major resources you modified, including their
package name/URLs, if exist, and **open-source license type**

I would also like to see the software license for each of the added components/artworks/fonts you used, can you add those to the README file?

**Comment by ivonne0126** [comment]
Professor, when you say license type, do you mean just add MIT License or Copy left license?

**Comment by fangq** [comment]
thank you, merged

**Pull request merged**
